title:             QT's Blog
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            QT
baseurl:           "/"
url:               "http://qt06.gitee.io"

# Social Profiles
twitter_username:  qt06com
github_username:   qt06
facebook_username: qt10011

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
